name: carrello_leggero
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.5

dependencies:
  cached_network_image: ^3.4.1
  dio: ^5.9.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.3.1
  freezed_annotation: ^3.1.0
  go_router: ^17.2.3
  json_annotation: ^4.11.0
  pretty_dio_logger: ^1.4.0
  riverpod_annotation: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  json_serializable: ^6.13.2
  build_runner: ^2.15.0
  freezed: ^3.2.5

flutter:
  uses-material-design: true

  fonts:
    - family: Public Sans
      fonts:
        - asset: assets/fonts/PublicSans-Regular.ttf
        - asset: assets/fonts/PublicSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/PublicSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/PublicSans-Bold.ttf
          weight: 700
